site_name: WashU Physics Department Documentation
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Printers: printers.md
  - Physics Cluster: physics-hpc.md
  - RIS: ris.md
  - Contribute: contribute.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem


extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6

site_dir: 'public'
